### ISSUE TITLE
G729 Codec

### ISSUE THREAD

**Issue by brahmanzadeh** [sipsorcery/sipsorcery-media#6]
Hello guys,
I am newbie in SipSorcery and VOIP, as well. I successfully used your sample codes to place calls to a VOIP server and record audio, building in .NET core 3.1. I have noticed that SipSorcery is designed to work with G711 ulaw and alaw, or better to say, non-compressed audio quality. 
I am just wondering if it is possible to implement G729 codec for SipSorcery Media. Any guidance and tutorial will be appreciated.

**Comment by sipsorcery** [comment]
There is also G722 support if you're looking for a wideband codec.

As far as G729 goes there does look like there is at least one C# port available [here](https://github.com/jongoochgithub/GroovyCodecs). To use it with the [sipsorcery library](https://github.com/sipsorcery/sipsorcery) would require tweaking that implementation so that it works with packets rather than reading and writing file streams. The codec could then be added to the other [supported ones](https://github.com/sipsorcery/sipsorcery/tree/master/src/app/Media/Codecs).

An alternative is to use `ffmpeg's` `libavcodec` but that is probably only useful if you're doing some sort of C++ application.

**Comment by brahmanzadeh** [comment]
Thanks for your quick reply. I have started playing around with your hints.

**Comment by brahmanzadeh** [comment]
> There is also G722 support if you're looking for a wideband codec.
> 
> As far as G729 goes there does look like there is at least one C# port available [here](https://github.com/jongoochgithub/GroovyCodecs). To use it with the [sipsorcery library](https://github.com/sipsorcery/sipsorcery) would require tweaking that implementation so that it works with packets rather than reading and writing file streams. The codec could then be added to the other [supported ones](https://github.com/sipsorcery/sipsorcery/tree/master/src/app/Media/Codecs).
> 
> An alternative is to use `ffmpeg's` `libavcodec` but that is probably only useful if you're doing some sort of C++ application.

This C++ part of sipsorcery-media library is killing me ;). Full of dependencies and C++ stuffs which I couldn't handle until now. Making change in SipSorcery library its self was easy, peace a cake, because of its C# nature.
By any chance, is there a short-cut to implement or even just check performance of Groovy's G729 codec on SipSorcery? Or do you have any plan to implement this Codec on SipSorcery?

**Comment by sipsorcery** [comment]
If you're adding the codec as a pure C# implementation you don't need to change the `SIPSorceryMedia` library at all. Instead add the codec to the `SIPSorcery` library in the directory I mentioned above [src/app/media/codecs](https://github.com/sipsorcery/sipsorcery/tree/master/src/app/Media/Codecs).

**Comment by brahmanzadeh** [comment]
Dear Aaron,
I'd like to thank you for your hints. This issue was 100 percent solved by your kind help. I've successfully embedded Groovy's G729 codec into SipSorcery.

**Comment by sipsorcery** [comment]
If you're able to share your code a PR would be welcome :).
